fixed an oopsie + some more code refactoring
Unhandled exception! AttributeError: 'Line' object has no attribute 'active' (can't send messages lol)
+ put background drawing code into a global loop so it's not scene-based anymore